name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup NodeJS"
        uses: actions/setup-node@v2
        with:
          node-version: 12.13.1

      - name: "Install NPM Packages"
        run: npm install
