name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Remove Package Lock"
        uses: rm -rf package-lock.json

      - name: "Setup NodeJS"
        uses: actions/setup-node@v2
        with:
          node-version: 12.13.1

      - name: "Install NPM Packages"
        run: npm install

      - name: "Run Tests"
        run: npm run tests
